set(SOURCES
	src/ArmorAddons.h
	src/ArmorAddons.cpp
	src/Armors.h
	src/Armors.cpp
	src/Cells.h
	src/Cells.cpp
	src/CObjs.h
	src/CObjs.cpp
	src/DefaultObjectManagers.h
	src/DefaultObjectManagers.cpp
	src/FormLists.h
	src/FormLists.cpp
	src/Ingestibles.h
	src/Ingestibles.cpp
	src/Keywords.h
	src/Keywords.cpp
	src/LeveledLists.h
	src/LeveledLists.cpp
	src/Locations.h
	src/Locations.cpp
	src/MusicTypes.h
	src/MusicTypes.cpp
	src/NPCs.h
	src/NPCs.cpp
	src/ObjectModifications.h
	src/ObjectModifications.cpp
	src/Outfits.h
	src/Outfits.cpp
	src/Quests.h
	src/Quests.cpp
	src/Races.h
	src/Races.cpp
	src/Weapons.h
	src/Weapons.cpp
	src/Worldspaces.h
	src/Worldspaces.cpp
	src/Configs.h
	src/Configs.cpp
	src/ConfigUtils.h
	src/Parsers.h
	src/Parsers.cpp
	src/Utils.h
	src/Utils.cpp
	src/PCH.h
	src/main.cpp
)
