set(SOURCES
	include/ArmorAddons.h
	include/Armors.h
	include/Cells.h
	include/CObjs.h
	include/CombatStyles.h
	include/Containers.h
	include/DefaultObjectManagers.h
	include/FormLists.h
	include/ImageSpaceAdapters.h
	include/Ingestibles.h
	include/Keywords.h
	include/LeveledLists.h
	include/Locations.h
	include/MusicTypes.h
	include/NPCs.h
	include/ObjectModifications.h
	include/Outfits.h
	include/Quests.h
	include/Races.h
	include/Weapons.h
	include/WorldSpaces.h
	include/Configs.h
	include/ConfigUtils.h
	include/Parsers.h
	include/Utils.h
	src/PCH.h
	src/ArmorAddons.cpp
	src/Armors.cpp
	src/Cells.cpp
	src/CObjs.cpp
	src/CombatStyles.cpp
	src/Containers.cpp
	src/DefaultObjectManagers.cpp
	src/FormLists.cpp
	src/ImageSpaceAdapters.cpp
	src/Ingestibles.cpp
	src/Keywords.cpp
	src/LeveledLists.cpp
	src/Locations.cpp
	src/MusicTypes.cpp
	src/NPCs.cpp
	src/ObjectModifications.cpp
	src/Outfits.cpp
	src/Quests.cpp
	src/Races.cpp
	src/Weapons.cpp
	src/WorldSpaces.cpp
	src/Configs.cpp
	src/Parsers.cpp
	src/Utils.cpp
	src/main.cpp
)
