set(SOURCES
	src/CObjs.h
	src/CObjs.cpp
	src/FormLists.h
	src/FormLists.cpp
	src/Ingestibles.h
	src/Ingestibles.cpp
	src/Keywords.h
	src/Keywords.cpp
	src/LeveledLists.h
	src/LeveledLists.cpp
	src/Races.h
	src/Races.cpp
	src/Configs.h
	src/Configs.cpp
	src/Utils.h
	src/Utils.cpp
	src/PCH.h
	src/main.cpp
)
